name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11 

      - run: bun install
      - run: bun run build
      - run: docker build . --file Dockerfile -t mosecoza/ciao-chow
